      - name: Accept Android Licenses & Set SDK Path
        run: |
          yes | sdkmanager --licenses || true
          
          # Android directory check karein
          if [ -d "android" ]; then
            PROJECT_DIR="android"
          else
            PROJECT_DIR="."
          fi
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

          # local.properties create karein
          echo "sdk.dir=$ANDROID_HOME" > $PROJECT_DIR/local.properties

      - name: Prepare Gradlew and Permissions
        run: |
          cd ${{ env.PROJECT_DIR }}

          if [ ! -f "gradlew" ]; then
            echo "gradlew not found, generating wrapper..."
            gradle wrapper
          fi

          chmod +x gradlew

      - name: Build Debug APK
        run: |
          cd ${{ env.PROJECT_DIR }}
          ./gradlew assembleDebug --no-daemon --info
